# Generated by Django 5.1 on 2025-01-22 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_image/', verbose_name='本の写真')),
                ('content', models.TextField(max_length=1000, verbose_name='感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('book_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='本の題名')),
                ('book_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
                'ordering': ['-created_at'],
            },
        ),
    ]
